version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cleanoraadmin_miahkykh

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "0000"
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: cleonora_database
    depends_on:
      - db
    networks:
      - cleanoraadmin_miahkykh

volumes:
  postgres_data:

networks:
  cleanoraadmin_miahkykh:
    driver: bridge
