name: Build and push CleanoraAdmin image and restart containers
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build app with Gradle
        run: |
          ./gradlew build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push CleonoraAdmin image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cleonoraadmin-miahkykh:latest

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Deploying CleonoraAdmin with Docker Compose"
            docker-compose -v || (echo "Docker Compose is not installed. Please install it." && exit 1)
            docker -v || (echo "Docker is not installed. Please install it." && exit 1)
            scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/tmp/docker-compose.yml docker-compose.yml
            docker compose -f /tmp/docker-compose.yml pull
            docker compose -f /tmp/docker-compose.yml up -d
            rm -f /tmp/docker-compose.yml
            echo "CleonoraAdmin has been deployed"
