name: Build and push coffeeapp image and restart containers
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build app with Gradle
        run: |
          ./gradlew build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push CleonoraAdmin image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cleonora-miahkykh:latest

      - name: SSH Restart PostgreSQL container
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            docker network ls | grep -q "cleonora-network" || docker network create cleonora-network
            echo "Restarting PostgreSQL container"

            docker stop cleonora-db || echo "PostgreSQL container not running"
            docker rm cleonora-db || echo "PostgreSQL container not found"
            docker pull postgres:latest
            docker run -d --name cleonora-db --net cleonora-network -e POSTGRES_PASSWORD=0000 -e POSTGRES_DB=postgres -p 5440:5432 postgres:latest
            echo "PostgreSQL container has been updated"

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: docker-compose.yml
          target: /home/slj/projects/CleonoraApp-R.Miahkykh

      - name: SSH Restart CleonoraAdmin container
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            docker network ls | grep -q "cleonora-network" || docker network create cleonora-network
            cd /home/slj/projects/CleonoraApp-R.Miahkykh
            docker compose pull
            docker-compose up -d
